version: '3.8'
services:
  mongodb:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
    links:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    links:
      - backend

volumes:
  dbdata:
